# Generated by Django 5.0.6 on 2024-05-24 08:06

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to=home.models.save_news_img),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, upload_to=home.models.save_logo),
        ),
    ]
