# Generated by Django 5.0.6 on 2024-05-30 05:49

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, upload_to=home.models.save_events_img),
        ),
    ]
