# Generated by Django 5.0.6 on 2024-06-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_socialmediaurls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaurls',
            name='facebook',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediaurls',
            name='instagram',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediaurls',
            name='twitter',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
