# Generated by Django 5.0.6 on 2024-06-05 07:37

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_socialmediaurls_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_title', models.CharField(blank=True, max_length=255)),
                ('children_text', models.TextField(blank=True)),
                ('children_image', models.ImageField(blank=True, upload_to=home.models.save_info_img)),
                ('parent_title', models.CharField(blank=True, max_length=255)),
                ('parent_text', models.TextField(blank=True)),
                ('parent_image', models.ImageField(blank=True, upload_to=home.models.save_info_img)),
            ],
        ),
    ]
