# Generated by Django 5.0.6 on 2024-06-05 07:40

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_mainpageinfos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpageinfos',
            name='about_image',
            field=models.ImageField(blank=True, upload_to=home.models.save_info_img),
        ),
        migrations.AddField(
            model_name='mainpageinfos',
            name='about_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mainpageinfos',
            name='about_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainpageinfos',
            name='home_image',
            field=models.ImageField(blank=True, upload_to=home.models.save_info_img),
        ),
        migrations.AddField(
            model_name='mainpageinfos',
            name='home_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mainpageinfos',
            name='home_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
