# Generated by Django 5.0.6 on 2024-06-05 07:44

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_mainpageinfos_about_image_mainpageinfos_about_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=home.models.save_info_img)),
            ],
        ),
        migrations.DeleteModel(
            name='MainPageInfos',
        ),
    ]
