# Generated by Django 5.0.6 on 2024-05-29 10:26

import members_area.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('files', models.FileField(upload_to=members_area.models.save_mevents_files)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='membersevents',
            name='image',
            field=models.ImageField(blank=True, upload_to=members_area.models.save_mevents_img),
        ),
    ]
