# Generated by Django 5.0.6 on 2024-05-30 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_area', '0003_membersmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersmessage',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
