# Generated by Django 5.0.6 on 2024-06-05 08:08

import members_area.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members_area', '0005_rename_message_membersmessage_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersPageInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to=members_area.models.save_main_img)),
            ],
        ),
    ]
